# 1. Реализуйте метод, который запрашивает у пользователя ввод дробного числа (типа float), и возвращает введенное значение.
# Ввод текста вместо числа не должно приводить к падению приложения, вместо этого, необходимо повторно запросить у пользователя ввод данных.


def float_input():
    while True:
        try:
            return float(input("Введите дробное число: "))
        except ValueError:
            print("Введены некорректные данные! Введите дробное число:")


print(f"Введённое число: {float_input()}")



# 2. Если необходимо, исправьте данный код
# (задание 2 https://docs.google.com/document/d/17EaA1lDxzD5YigQ5OAal60fOFKVoCbEJqooB9XfhT7w/edit)


try {
   int d = 0;
   double catchedRes1 = intArray[8] / d;
   System.out.println("catchedRes1 = " + catchedRes1);
} catch (ArithmeticException e) {
   System.out.println("Catching exception: " + e);
} catch (IndexOutOfBoundsException e) {
   System.out.println("Catching exception: " + e);
}



# 3. Дан следующий код, исправьте его там, где требуется
# (задание 3 https://docs.google.com/document/d/17EaA1lDxzD5YigQ5OAal60fOFKVoCbEJqooB9XfhT7w/edit)


public static void main(String[] args) {
   try {
       int a = 90;
       int b = 3;
       System.out.println(a / b);
       printSum(23, 234);
       int[] abc = { 1, 2, 3 };
       abc[3] = 9;
   } catch (NullPointerException ex) {
       System.out.println("Указатель не может указывать на null!");
   } catch (IndexOutOfBoundsException ex) {
       System.out.println("Массив выходит за пределы своего размера!");
   } catch (Throwable ex) {
       System.out.println("Что-то пошло не так...");
   }
}
public static void printSum(Integer a, Integer b) {
   System.out.println(a + b);
}



